<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="02_inertia_macro.xacro"/>
  

  <link name="base_link" />

  <!-- Chassis -->
  <link name="chassis">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${base_lx} ${base_ly} ${base_lz}" />
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${base_lx} ${base_ly} ${base_lz}" />
      </geometry>
      <material name="Orange" />
    </visual>
    
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="${base_mass}"/>
      <xacro:box_inertia mass="${base_mass}" width="${base_ly}" height="${base_lz}" depth="${base_lx}"/>
    </inertial>
  </link>

  <joint name="chassis_joint" type="fixed">
    <origin xyz="0 0 ${base_lz/2+wheel_radius}" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="chassis" />
  </joint>

  <link name="virtual_rear_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
        <geometry>
          <cylinder length="0.01" radius="${wheel_radius}"/>
        </geometry>
        <material name="invisible"/>
      </visual>
  </link>

  <joint name="virtual_rear_wheel_joint" type="continuous">
      <parent link="chassis"/>
      <child link="virtual_rear_wheel"/>
      <origin xyz="-${base_lx/2} 0 -${base_lz/2}" rpy="0 0 ${PI/2}"/>
      <axis xyz="1 0 0"/>
      <limit effort="100.0" velocity="100.0"/>
      <dynamics damping="0.2"/>
  </joint>

  <!-- left wheel Link -->
  <link name="back_wheel">
    <collision>
      <geometry>
        <cylinder length="${wheel_len*4}" radius="${wheel_radius}" /> 
      </geometry>
    </collision>
    <visual>
      <geometry>
        <cylinder length="${wheel_len*4}" radius="${wheel_radius}" /> 
      </geometry>
      <material name="Black" />
    </visual>

    <inertial>
      <mass value="${wheel_mass}" />
      <xacro:cylinder_inertia mass="${wheel_mass}" radius="${wheel_radius}" height="${wheel_len*4}"/>
    </inertial>
  </link>

  <joint name="back_wheel_joint" type="continuous">
    <origin xyz="-${base_lx/2} 0 ${wheel_radius}" rpy="-1.57 0 0" />
    <parent link="base_link" />
    <child link="back_wheel" />
    <axis xyz="0 0 1" />
    <dynamics damping="0.2" />
  </joint>

    <!-- Steering Link -->
  <link name="front_steering_link">
    <visual>
      <geometry>
        <box size="0.01 0.01 0.01" />
      </geometry>
      <material name="Black" />
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="0.005" />
      <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1" />
    </inertial>
  </link>

  <joint name="front_steering_joint" type="revolute">
    <origin xyz="${base_lx/2} 0 ${wheel_radius}" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="front_steering_link" />
    <axis xyz="0 0 1" />
    <limit effort="100.0" lower="-0.785398" upper="0.785398" velocity="0.1"/>
  </joint>
  
  <!-- right wheel Link -->
  <link name="front_wheel">
    <collision>
      <geometry>
        <cylinder length="${wheel_len*4}" radius="${wheel_radius}" />
      </geometry>
    </collision>
    <visual>
      <geometry>
        <cylinder length="${wheel_len*4}" radius="${wheel_radius}" />
      </geometry>
      <material name="Black" />
    </visual>

    <inertial>
      <mass value="${wheel_mass}" />
      <xacro:cylinder_inertia mass="${wheel_mass}" radius="${wheel_radius}" height="${wheel_len*4}"/>
    </inertial>
  </link>

  <joint name="front_wheel_joint" type="continuous">
    <mimic joint="back_wheel_joint"/>
    <origin xyz="0 0 0" rpy="-1.57 0 0" />
    <parent link="front_steering_link" />
    <child link="front_wheel" />
    <axis xyz="0 0 1" />
    <dynamics damping="0.2" />
  </joint>

</robot>
