<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="02_inertia_macro.xacro"/>
  

  <link name="base_link" />

  <!-- Chassis -->
  <link name="chassis">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${base_lx} ${base_ly} ${base_lz}" />
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${base_lx} ${base_ly} ${base_lz}" />
      </geometry>
      <material name="Orange" />
    </visual>
    
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="${base_mass}"/>
      <xacro:box_inertia mass="${base_mass}" width="${base_ly}" height="${base_lz}" depth="${base_lx}"/>
    </inertial>
  </link>


  <joint name="chassis_joint" type="fixed">
    <origin xyz="${base_lx/2} 0 ${base_lz/2+wheel_radius*2}" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="chassis" />
  </joint>

  <!-- left wheel Link -->
  <link name="left_wheel">
    <collision>
      <geometry>
        <sphere radius="${wheel_radius}" />
      </geometry>
    </collision>
    <visual>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_radius}" /> 
      </geometry>
      <material name="Black" />
    </visual>

    <inertial>
      <mass value="${wheel_mass}" />
      <xacro:cylinder_inertia mass="${wheel_mass}" radius="${wheel_radius}" height="${wheel_len}"/>
    </inertial>
  </link>

  <joint name="left_wheel_joint" type="continuous">
    <mimic joint="left_traction_joint"/>
    <origin xyz="-${base_lx/2} ${base_ly/2+wheel_len/2} -${base_lz/2}" rpy="-1.57 0 0" />
    <parent link="chassis" />
    <child link="left_wheel" />
    <axis xyz="0 0 1" />
    <dynamics damping="0.2" />
  </joint>

  <!-- right wheel Link -->
  <link name="right_wheel">
    <collision>
      <geometry>
        <sphere radius="${wheel_radius}" />
      </geometry>
    </collision>
    <visual>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_radius}" />
      </geometry>
      <material name="Black" />
    </visual>

    <inertial>
      <mass value="${wheel_mass}" />
      <xacro:cylinder_inertia mass="${wheel_mass}" radius="${wheel_radius}" height="${wheel_len}"/>
    </inertial>
  </link>

  <joint name="right_wheel_joint" type="continuous">
    <mimic joint="left_traction_joint"/>
    <origin xyz="-${base_lx/2} -${base_ly/2+wheel_len/2} -${base_lz/2}" rpy="-1.57 0 0" />
    <parent link="chassis" />
    <child link="right_wheel" />
    <axis xyz="0 0 1" />
    <dynamics damping="0.2" />
  </joint>

  <!-- Steering Link -->
  <link name="left_steering_link">
    <visual>
      <geometry>
        <box size="0.01 0.01 0.01" />
      </geometry>
      <material name="Black" />
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="0.005" />
      <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1" />
    </inertial>
  </link>

  <joint name="left_steering_joint" type="revolute">
    <origin xyz="${base_lx/2} ${base_ly/2+wheel_len/2} -${base_lz/2}" rpy="0 0 0" />
    <parent link="chassis" />
    <child link="left_steering_link" />
    <axis xyz="0 0 1" />
    <limit effort="100.0" lower="-0.785398" upper="0.785398" velocity="0.1"/>
  </joint>

  <!-- traction wheel link -->
  <link name="left_wheel_front_link">
    <visual>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_radius}" />
      </geometry>
      <material name="Black" />
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="${wheel_mass}" />
      <xacro:cylinder_inertia mass="${wheel_mass}" radius="${wheel_radius}" height="${wheel_len}"/>
    </inertial>
    <collision>
      <geometry>
        <sphere radius="${wheel_radius}" />
      </geometry>
    </collision>
  </link>

  <joint name="left_traction_joint" type="continuous">
    <parent link="left_steering_link" />
    <child link="left_wheel_front_link" />
    <origin xyz="0 0 0" rpy="-1.57 1.57 0" />
    <axis xyz="0 0 1" />
  </joint>

  <!-- ============== right streering ================= -->

   <!-- Steering Link -->
  <link name="right_steering_link">
    <visual>
      <geometry>
        <box size="0.01 0.01 0.01" />
      </geometry>
      <material name="Black" />
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="0.005" />
      <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1" />
    </inertial>
  </link>

  <joint name="right_steering_joint" type="revolute">
    <mimic joint="left_steering_joint"/>
    <origin xyz="${base_lx/2} -${base_ly/2+wheel_len/2} -${base_lz/2}" rpy="0 0 0" />
    <parent link="chassis" />
    <child link="right_steering_link" />
    <axis xyz="0 0 1" />
    <limit effort="100.0" lower="-0.785398" upper="0.785398" velocity="0.1"/>
  </joint>

  <!-- traction wheel link -->
  <link name="right_wheel_front_link">
    <visual>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_radius}" />
      </geometry>
      <material name="Black" />
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="${wheel_mass}" />
      <xacro:cylinder_inertia mass="${wheel_mass}" radius="${wheel_radius}" height="${wheel_len}"/>
    </inertial>
    <collision>
      <geometry>
        <sphere radius="${wheel_radius}" />
      </geometry>
    </collision>
  </link>

  <joint name="right_traction_joint" type="continuous">
    <mimic joint="left_traction_joint"/>
    <parent link="right_steering_link" />
    <child link="right_wheel_front_link" />
    <origin xyz="0 0 0" rpy="-1.57 1.57 0" />
    <axis xyz="0 0 1" />
  </joint>


</robot>
